// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tech_share.proto

package pkg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonRequest) Reset()         { *m = PersonRequest{} }
func (m *PersonRequest) String() string { return proto.CompactTextString(m) }
func (*PersonRequest) ProtoMessage()    {}
func (*PersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6130c70328736bb3, []int{0}
}

func (m *PersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonRequest.Unmarshal(m, b)
}
func (m *PersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonRequest.Marshal(b, m, deterministic)
}
func (m *PersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonRequest.Merge(m, src)
}
func (m *PersonRequest) XXX_Size() int {
	return xxx_messageInfo_PersonRequest.Size(m)
}
func (m *PersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PersonRequest proto.InternalMessageInfo

func (m *PersonRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PeopleRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeopleRequest) Reset()         { *m = PeopleRequest{} }
func (m *PeopleRequest) String() string { return proto.CompactTextString(m) }
func (*PeopleRequest) ProtoMessage()    {}
func (*PeopleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6130c70328736bb3, []int{1}
}

func (m *PeopleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeopleRequest.Unmarshal(m, b)
}
func (m *PeopleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeopleRequest.Marshal(b, m, deterministic)
}
func (m *PeopleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeopleRequest.Merge(m, src)
}
func (m *PeopleRequest) XXX_Size() int {
	return xxx_messageInfo_PeopleRequest.Size(m)
}
func (m *PeopleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeopleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeopleRequest proto.InternalMessageInfo

func (m *PeopleRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Person struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_6130c70328736bb3, []int{2}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_6130c70328736bb3, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func init() {
	proto.RegisterType((*PersonRequest)(nil), "pkg.PersonRequest")
	proto.RegisterType((*PeopleRequest)(nil), "pkg.PeopleRequest")
	proto.RegisterType((*Person)(nil), "pkg.Person")
	proto.RegisterType((*Address)(nil), "pkg.Address")
}

func init() { proto.RegisterFile("tech_share.proto", fileDescriptor_6130c70328736bb3) }

var fileDescriptor_6130c70328736bb3 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x02, 0x8d, 0x72, 0x05, 0x84, 0x4e, 0x0c, 0x11, 0x0b, 0x91, 0x25, 0x50, 0xa6,
	0x08, 0xca, 0xc0, 0xcc, 0xc4, 0xc2, 0x80, 0x4c, 0x77, 0x14, 0x92, 0x53, 0x63, 0xb5, 0x8d, 0x83,
	0x7d, 0x1d, 0xfa, 0xef, 0x51, 0x1c, 0x07, 0xb5, 0xdd, 0xee, 0x9e, 0xdf, 0x7d, 0xbe, 0x77, 0x70,
	0xc3, 0x54, 0xb7, 0xdf, 0xae, 0xad, 0x2c, 0x95, 0xbd, 0x35, 0x6c, 0x30, 0xee, 0xd7, 0x2b, 0x79,
	0x0f, 0x57, 0x9f, 0x64, 0x9d, 0xe9, 0x14, 0xfd, 0xee, 0xc8, 0x31, 0x5e, 0x43, 0xa4, 0x9b, 0x4c,
	0xe4, 0xa2, 0x88, 0x55, 0xa4, 0x1b, 0xf9, 0x30, 0x18, 0x4c, 0xbf, 0xa1, 0xc9, 0x70, 0x0b, 0x17,
	0x1b, 0xbd, 0xd5, 0x1c, 0x3c, 0x63, 0x23, 0x97, 0x30, 0x1b, 0x39, 0xa7, 0x00, 0x44, 0x38, 0xef,
	0xaa, 0x2d, 0x65, 0x51, 0x2e, 0x8a, 0x54, 0xf9, 0x1a, 0x1f, 0x21, 0xa9, 0x9a, 0xc6, 0x92, 0x73,
	0x59, 0x9c, 0x8b, 0x62, 0xbe, 0xb8, 0x2c, 0xfb, 0xf5, 0xaa, 0x7c, 0x1b, 0x35, 0x35, 0x3d, 0xca,
	0x57, 0x48, 0x82, 0x36, 0x60, 0x6a, 0xcd, 0x7b, 0x0f, 0x4e, 0x95, 0xaf, 0x31, 0x83, 0xa4, 0x36,
	0xbb, 0x8e, 0xed, 0x3e, 0xd0, 0xa7, 0x76, 0xd1, 0x41, 0xba, 0xa4, 0xba, 0xfd, 0x1a, 0xe2, 0x62,
	0x09, 0xe9, 0x3b, 0x71, 0x58, 0x0f, 0xfd, 0x4f, 0x47, 0x99, 0xef, 0xe6, 0x07, 0x9a, 0x3c, 0xc3,
	0x67, 0x80, 0x0f, 0xed, 0x78, 0x8c, 0xfd, 0x3f, 0x70, 0x70, 0x83, 0x93, 0x81, 0x27, 0xf1, 0x33,
	0xf3, 0x27, 0x7d, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xec, 0x12, 0x48, 0xfa, 0x66, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TechShareClient is the client API for TechShare service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TechShareClient interface {
	GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*Person, error)
	ListPeople(ctx context.Context, in *PeopleRequest, opts ...grpc.CallOption) (TechShare_ListPeopleClient, error)
}

type techShareClient struct {
	cc *grpc.ClientConn
}

func NewTechShareClient(cc *grpc.ClientConn) TechShareClient {
	return &techShareClient{cc}
}

func (c *techShareClient) GetPerson(ctx context.Context, in *PersonRequest, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/pkg.TechShare/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *techShareClient) ListPeople(ctx context.Context, in *PeopleRequest, opts ...grpc.CallOption) (TechShare_ListPeopleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TechShare_serviceDesc.Streams[0], "/pkg.TechShare/ListPeople", opts...)
	if err != nil {
		return nil, err
	}
	x := &techShareListPeopleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TechShare_ListPeopleClient interface {
	Recv() (*Person, error)
	grpc.ClientStream
}

type techShareListPeopleClient struct {
	grpc.ClientStream
}

func (x *techShareListPeopleClient) Recv() (*Person, error) {
	m := new(Person)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TechShareServer is the server API for TechShare service.
type TechShareServer interface {
	GetPerson(context.Context, *PersonRequest) (*Person, error)
	ListPeople(*PeopleRequest, TechShare_ListPeopleServer) error
}

func RegisterTechShareServer(s *grpc.Server, srv TechShareServer) {
	s.RegisterService(&_TechShare_serviceDesc, srv)
}

func _TechShare_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TechShareServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.TechShare/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TechShareServer).GetPerson(ctx, req.(*PersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TechShare_ListPeople_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeopleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TechShareServer).ListPeople(m, &techShareListPeopleServer{stream})
}

type TechShare_ListPeopleServer interface {
	Send(*Person) error
	grpc.ServerStream
}

type techShareListPeopleServer struct {
	grpc.ServerStream
}

func (x *techShareListPeopleServer) Send(m *Person) error {
	return x.ServerStream.SendMsg(m)
}

var _TechShare_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.TechShare",
	HandlerType: (*TechShareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _TechShare_GetPerson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPeople",
			Handler:       _TechShare_ListPeople_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tech_share.proto",
}
